### ISSUE TITLE
Smoother spectral degradation

### ISSUE THREAD

**Issue by hippke** [jlustigy/coronagraph#4]
Very cool project! 
In the example "Degrading a spectrum" from the docs, the last Figure shows some jitter. Sometimes, higher resolution results in lower albedo. I understand that this comes from the grid placement, as can be seen in the second-to-last Figure. 
- If the grid placement can be chosen in advance, it can be optimized on a (one?) certain wavelength. Then, one could test the optimal placement. 
- If the grid placement is not optimized, it would be more useful to show the _average_ albedo. This could be done by iterating over a grid (or random set) of placements.

In both cases, the last Figure would be downward sloping.

**Comment by jlustigy** [comment]
Thanks @hippke – This is a great point! The jitter seen in the last figure in that example (pasted below) does indeed come from the naive/non-optimal placement of the grid: 

![notebooks_degrading_a_spectrum_22_0](https://user-images.githubusercontent.com/8882466/63615272-cc506600-c599-11e9-82e4-da15e1537889.png)

By default, the photon count rate calculation determines the wavelength grid from the min and max wavelengths (`Telescope.lammin` and `Telescope.lammax`) and the spectral resolving power (`Telescope.resolution`) that the user provides. However, the user can optionally provide the wavelength and delta-wavelength grids by setting `Telescope.lam` and `Telescope.dlam` before performing the noise calculations.  

Within this simpler example, you are absolutely right, the optimal grid placement and average albedo could be found by iterating the minimum wavelength over a grid that spans the width of the wavelength interval at the oxygen A-band. Then the optimal grid solution could be manually passed into subsequent S/N calculations, using the method I described above. 

I would be happy to add this calculation and discussion to this example if you think others would find it useful!

**Comment by jlustigy** [comment]
Just to follow up on this, I updated [this example in the docs](https://jlustigy.github.io/coronagraph/notebooks/degrading_a_spectrum.html#Optimal-Resolution-for-Observing-Earth's-O-A-band) to address this comment. The bottom line is that the above curve can indeed be smoothed by optimizing the placement of the wavelength grid: 
![notebooks_degrading_a_spectrum_24_0](https://user-images.githubusercontent.com/8882466/63713112-da012800-c7f3-11e9-81aa-6214a8be9dc6.png)
Thanks @hippke for pointing this out!
