### ISSUE TITLE
Don't use nbsphinx_prompt_width to hide prompts

### ISSUE THREAD

**Issue by mgeier** [jlustigy/coronagraph#9]
I'm creating this issue because your repo contains a `conf.py` file with

```python
nbsphinx_prompt_width = 0
```

... presumably in an attempt to remove the prompts from code cells.

I just want to give you a heads-up that this will stop working once https://github.com/spatialaudio/nbsphinx/pull/439 is merged.

For more reliable alternatives, see https://nbsphinx.readthedocs.io/en/latest/custom-css.html.

**Comment by jlustigy** [comment]
Fixed in [this commit](https://github.com/jlustigy/coronagraph/commit/977987497166b7a88018a9190eb7db44ee4a64d1). Thanks for the heads up!
